# Generated by Django 2.2.5 on 2019-11-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='logclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.TextField(max_length=20)),
                ('pswd1', models.TextField(max_length=20)),
                ('pswd2', models.TextField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('correct_option', models.TextField(max_length=200)),
                ('option1', models.TextField(max_length=200)),
                ('option2', models.TextField(max_length=200)),
                ('option3', models.TextField(max_length=200)),
                ('option4', models.TextField(max_length=200)),
                ('points', models.IntegerField()),
                ('quiz', models.TextField(max_length=200)),
            ],
        ),
    ]
