# Generated by Django 2.2.5 on 2019-11-14 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='logclass',
            new_name='registartion',
        ),
    ]
