# Generated by Django 2.2.5 on 2019-11-14 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_auto_20191114_1811'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='registartion',
            new_name='registration',
        ),
    ]
