# Generated by Django 2.2.5 on 2019-11-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20191114_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
    ]
