# Generated by Django 2.2.5 on 2019-11-14 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20191114_1914'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='question',
            new_name='questions',
        ),
    ]
