# Generated by Django 2.2.5 on 2019-11-14 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20191114_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='option1',
            new_name='options',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option2',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option3',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='option4',
        ),
    ]
